apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-peliculas-backend-configmap
  namespace: default
data:
  application.yml: |
    spring:
      application:
        name: ms-peliculas-backend
      datasource:
        url: jdbc:oracle:thin:@//oracle-db:1521/XEPDB1
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: oracle.jdbc.OracleDriver
      profiles:
        active: dev
    server:
      port: 9091
    management:
      endpoints:
        web:
          exposure:
            include: "*"
      endpoint:
        health:
          show-details: always
          probes:
            enabled: true
      health:
        livenessState:
          enabled: true
        readinessState:
          enabled: true
