apiVersion: v1
kind: Service
metadata:
  name: ms-peliculas-backend-service
  namespace: default
spec:
  selector:
    app: ms-peliculas-backend
  ports:
  - protocol: TCP
    port: 9091
    targetPort: 9091
    nodePort: 30091
  type: NodePort
